//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTyping.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangStr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangStr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenTyping.Resources.Lang.LangStr", typeof(LangStr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenSource Mordern Keyboard Typing Trainer.
        /// </summary>
        internal static string AppDesc {
            get {
                return ResourceManager.GetString("AppDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenTyping.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long sentences.
        /// </summary>
        internal static string ArtPrac {
            get {
                return ResourceManager.GetString("ArtPrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice with one long sentence.
        /// </summary>
        internal static string ArtPracDesc {
            get {
                return ResourceManager.GetString("ArtPracDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average accuracy.
        /// </summary>
        internal static string AvgCorrect {
            get {
                return ResourceManager.GetString("AvgCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average speed.
        /// </summary>
        internal static string AvgSpeed {
            get {
                return ResourceManager.GetString("AvgSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11172 Charaters.
        /// </summary>
        internal static string Char11722 {
            get {
                return ResourceManager.GetString("Char11722", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2350 Characters.
        /// </summary>
        internal static string Char2350 {
            get {
                return ResourceManager.GetString("Char2350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accuracy.
        /// </summary>
        internal static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Keyboard.
        /// </summary>
        internal static string CurKeyboard {
            get {
                return ResourceManager.GetString("CurKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current sentences.
        /// </summary>
        internal static string CurPracData {
            get {
                return ResourceManager.GetString("CurPracData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select 2 or more keys to practice.
        /// </summary>
        internal static string ErrMsg1 {
            get {
                return ResourceManager.GetString("ErrMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate names exist.
        /// </summary>
        internal static string ErrMsg10 {
            get {
                return ResourceManager.GetString("ErrMsg10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Name field..
        /// </summary>
        internal static string ErrMsg11 {
            get {
                return ResourceManager.GetString("ErrMsg11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No KeyLayoutData field..
        /// </summary>
        internal static string ErrMsg12 {
            get {
                return ResourceManager.GetString("ErrMsg12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Character field..
        /// </summary>
        internal static string ErrMsg13 {
            get {
                return ResourceManager.GetString("ErrMsg13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextData field size is 0..
        /// </summary>
        internal static string ErrMsg14 {
            get {
                return ResourceManager.GetString("ErrMsg14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t exist TextData field..
        /// </summary>
        internal static string ErrMsg15 {
            get {
                return ResourceManager.GetString("ErrMsg15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column of numbers.
        /// </summary>
        internal static string ErrMsg16 {
            get {
                return ResourceManager.GetString("ErrMsg16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First row.
        /// </summary>
        internal static string ErrMsg17 {
            get {
                return ResourceManager.GetString("ErrMsg17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second row.
        /// </summary>
        internal static string ErrMsg18 {
            get {
                return ResourceManager.GetString("ErrMsg18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third row.
        /// </summary>
        internal static string ErrMsg19 {
            get {
                return ResourceManager.GetString("ErrMsg19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the same name already exists in the Keyboard data path..
        /// </summary>
        internal static string ErrMsg2 {
            get {
                return ResourceManager.GetString("ErrMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of key is .
        /// </summary>
        internal static string ErrMsg20 {
            get {
                return ResourceManager.GetString("ErrMsg20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to need, but .
        /// </summary>
        internal static string ErrMsg21 {
            get {
                return ResourceManager.GetString("ErrMsg21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to does not match .
        /// </summary>
        internal static string ErrMsg22 {
            get {
                return ResourceManager.GetString("ErrMsg22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forth row.
        /// </summary>
        internal static string ErrMsg23 {
            get {
                return ResourceManager.GetString("ErrMsg23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the same name already exists in the practice data path..
        /// </summary>
        internal static string ErrMsg3 {
            get {
                return ResourceManager.GetString("ErrMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be deleted because only one keyboard data exists..
        /// </summary>
        internal static string ErrMsg4 {
            get {
                return ResourceManager.GetString("ErrMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be deleted because only one practice data exists..
        /// </summary>
        internal static string ErrMsg5 {
            get {
                return ResourceManager.GetString("ErrMsg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of Hangul syllables in the file is one or less..
        /// </summary>
        internal static string ErrMsg6 {
            get {
                return ResourceManager.GetString("ErrMsg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while locating the application path..
        /// </summary>
        internal static string ErrMsg7 {
            get {
                return ResourceManager.GetString("ErrMsg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find keyborad data file. Please create keyboard data in that
        ///    path and try again..
        /// </summary>
        internal static string ErrMsg8 {
            get {
                return ResourceManager.GetString("ErrMsg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot fidn practice data file. Please create practice data in that path and try again..
        /// </summary>
        internal static string ErrMsg9 {
            get {
                return ResourceManager.GetString("ErrMsg9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluding upper key(Shift).
        /// </summary>
        internal static string ExceptShftKey {
            get {
                return ResourceManager.GetString("ExceptShftKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice is finished..
        /// </summary>
        internal static string FinishedPrac {
            get {
                return ResourceManager.GetString("FinishedPrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select practice data you want to practice..
        /// </summary>
        internal static string InfoMsg1 {
            get {
                return ResourceManager.GetString("InfoMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset statistic information.
        /// </summary>
        internal static string InitStatInfo {
            get {
                return ResourceManager.GetString("InitStatInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of pages.
        /// </summary>
        internal static string InPage {
            get {
                return ResourceManager.GetString("InPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard File data.
        /// </summary>
        internal static string KeyDataFile {
            get {
                return ResourceManager.GetString("KeyDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Keyboard File.
        /// </summary>
        internal static string KeyDataOpen {
            get {
                return ResourceManager.GetString("KeyDataOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard layout path.
        /// </summary>
        internal static string KeyDataPath {
            get {
                return ResourceManager.GetString("KeyDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        internal static string KeyPrac {
            get {
                return ResourceManager.GetString("KeyPrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice the position of each key on the keyboard..
        /// </summary>
        internal static string KeyPracDesc {
            get {
                return ResourceManager.GetString("KeyPracDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the position of the key you want to practice on/off..
        /// </summary>
        internal static string KeyPracHelp {
            get {
                return ResourceManager.GetString("KeyPracHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        internal static string Korean {
            get {
                return ResourceManager.GetString("Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your last speed:.
        /// </summary>
        internal static string LastSpeed {
            get {
                return ResourceManager.GetString("LastSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most mistyped key.
        /// </summary>
        internal static string MostWrongKey {
            get {
                return ResourceManager.GetString("MostWrongKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sentence practiced.
        /// </summary>
        internal static string NumPracSen {
            get {
                return ResourceManager.GetString("NumPracSen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice Data File.
        /// </summary>
        internal static string PracDataFile {
            get {
                return ResourceManager.GetString("PracDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentences path.
        /// </summary>
        internal static string PracDataPath {
            get {
                return ResourceManager.GetString("PracDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random arrangement of sentences.
        /// </summary>
        internal static string RanSenLoc {
            get {
                return ResourceManager.GetString("RanSenLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentences.
        /// </summary>
        internal static string SenPrac {
            get {
                return ResourceManager.GetString("SenPrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice by dividing it into short sentences.
        /// </summary>
        internal static string SenPracDesc {
            get {
                return ResourceManager.GetString("SenPracDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the sentence you want to practice by clicking on it..
        /// </summary>
        internal static string SenPracHelp {
            get {
                return ResourceManager.GetString("SenPracHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard layout.
        /// </summary>
        internal static string SetKeyboard {
            get {
                return ResourceManager.GetString("SetKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentences.
        /// </summary>
        internal static string SetPracData {
            get {
                return ResourceManager.GetString("SetPracData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SetProgramLang {
            get {
                return ResourceManager.GetString("SetProgramLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start practice.
        /// </summary>
        internal static string StartPrac {
            get {
                return ResourceManager.GetString("StartPrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syllables.
        /// </summary>
        internal static string SylPrac {
            get {
                return ResourceManager.GetString("SylPrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice by entering syllable units (Korean only) .
        /// </summary>
        internal static string SylPracDesc {
            get {
                return ResourceManager.GetString("SylPracDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2350 characters are practiced with the most frequently used in modern Hangul.
        /// </summary>
        internal static string SylPracHelp {
            get {
                return ResourceManager.GetString("SylPracHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User defined.
        /// </summary>
        internal static string UserDefined {
            get {
                return ResourceManager.GetString("UserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O&apos;zbek.
        /// </summary>
        internal static string Uzbek {
            get {
                return ResourceManager.GetString("Uzbek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected keyboard data.
        /// </summary>
        internal static string WarnMsg1 {
            get {
                return ResourceManager.GetString("WarnMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected practice data.
        /// </summary>
        internal static string WarnMsg2 {
            get {
                return ResourceManager.GetString("WarnMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        internal static string WarnMsg3 {
            get {
                return ResourceManager.GetString("WarnMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete statistical information?.
        /// </summary>
        internal static string WarnMsg4 {
            get {
                return ResourceManager.GetString("WarnMsg4", resourceCulture);
            }
        }
    }
}
