//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTyping.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangStr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangStr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenTyping.Resources.Lang.LangStr", typeof(LangStr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenSource Mordern Keyboard Typing Trainer.
        /// </summary>
        internal static string AppDesc {
            get {
                return ResourceManager.GetString("AppDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenTyping.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 긴글연습.
        /// </summary>
        internal static string ArtPrac {
            get {
                return ResourceManager.GetString("ArtPrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 하나의 장문을 대상으로 연습합니다..
        /// </summary>
        internal static string ArtPracDesc {
            get {
                return ResourceManager.GetString("ArtPracDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 평균 정확도.
        /// </summary>
        internal static string AvgCorrect {
            get {
                return ResourceManager.GetString("AvgCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 평균 타속.
        /// </summary>
        internal static string AvgSpeed {
            get {
                return ResourceManager.GetString("AvgSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 정확도.
        /// </summary>
        internal static string Correct {
            get {
                return ResourceManager.GetString("Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재 자판.
        /// </summary>
        internal static string CurKeyboard {
            get {
                return ResourceManager.GetString("CurKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재 연습 데이터.
        /// </summary>
        internal static string CurPracData {
            get {
                return ResourceManager.GetString("CurPracData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 삭제.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연습할 키를 2개 이상 선택해주세요..
        /// </summary>
        internal static string ErrMsg1 {
            get {
                return ResourceManager.GetString("ErrMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이름이 중복되게 존재합니다..
        /// </summary>
        internal static string ErrMsg10 {
            get {
                return ResourceManager.GetString("ErrMsg10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 이름(Name  필드)이 없습니다..
        /// </summary>
        internal static string ErrMsg11 {
            get {
                return ResourceManager.GetString("ErrMsg11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 키 레이아웃 (KeyLayoutData 필드) 가 없습니다..
        /// </summary>
        internal static string ErrMsg12 {
            get {
                return ResourceManager.GetString("ErrMsg12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 문자코드 종류(Character 필드)가 없습니다..
        /// </summary>
        internal static string ErrMsg13 {
            get {
                return ResourceManager.GetString("ErrMsg13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 글자 데이터(TextData 필드) 크기가 0입니다..
        /// </summary>
        internal static string ErrMsg14 {
            get {
                return ResourceManager.GetString("ErrMsg14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 글자 데이터(TextData 필드)가 없습니다..
        /// </summary>
        internal static string ErrMsg15 {
            get {
                return ResourceManager.GetString("ErrMsg15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 숫자 열.
        /// </summary>
        internal static string ErrMsg16 {
            get {
                return ResourceManager.GetString("ErrMsg16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 첫째 열.
        /// </summary>
        internal static string ErrMsg17 {
            get {
                return ResourceManager.GetString("ErrMsg17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 둘째 열.
        /// </summary>
        internal static string ErrMsg18 {
            get {
                return ResourceManager.GetString("ErrMsg18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 셋째 열.
        /// </summary>
        internal static string ErrMsg19 {
            get {
                return ResourceManager.GetString("ErrMsg19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 같은 이름의 파일이 이미 자판 데이터 경로에 존재합니다..
        /// </summary>
        internal static string ErrMsg2 {
            get {
                return ResourceManager.GetString("ErrMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 의 키의 개수는.
        /// </summary>
        internal static string ErrMsg20 {
            get {
                return ResourceManager.GetString("ErrMsg20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 가 필요하나.
        /// </summary>
        internal static string ErrMsg21 {
            get {
                return ResourceManager.GetString("ErrMsg21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 개로 일치하지 않습니다..
        /// </summary>
        internal static string ErrMsg22 {
            get {
                return ResourceManager.GetString("ErrMsg22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 같은 이름의 파일이 이미 연습 데이터 경로에 존재합니다..
        /// </summary>
        internal static string ErrMsg3 {
            get {
                return ResourceManager.GetString("ErrMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 자판 데이터가 한 개 존재하여 삭제할 수 없습니다..
        /// </summary>
        internal static string ErrMsg4 {
            get {
                return ResourceManager.GetString("ErrMsg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연습 데이터가 한 개 존재하여 삭제할 수 없습니다..
        /// </summary>
        internal static string ErrMsg5 {
            get {
                return ResourceManager.GetString("ErrMsg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 파일 내 한글 음절 개수가 1개 이하입니다..
        /// </summary>
        internal static string ErrMsg6 {
            get {
                return ResourceManager.GetString("ErrMsg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 응용 프로그램 경로를 찾는 도중 에러가 발생했습니다..
        /// </summary>
        internal static string ErrMsg7 {
            get {
                return ResourceManager.GetString("ErrMsg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 에서 자판 데이터 파일을 찾을 수 없습니다. 해당 경로에 자판 데이터를 생성하고 다시 시도하세요..
        /// </summary>
        internal static string ErrMsg8 {
            get {
                return ResourceManager.GetString("ErrMsg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 에서 연습 데이터 파일을 찾을 수 없습니다. 해당 경로에 연습 데이터를 생성하고 다시 시도하세요..
        /// </summary>
        internal static string ErrMsg9 {
            get {
                return ResourceManager.GetString("ErrMsg9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 윗글쇠(Shift)  연습 제외.
        /// </summary>
        internal static string ExceptShftKey {
            get {
                return ResourceManager.GetString("ExceptShftKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연습하실 연습 데이터를 선택해주세요..
        /// </summary>
        internal static string InfoMsg1 {
            get {
                return ResourceManager.GetString("InfoMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통계 정보 초기화.
        /// </summary>
        internal static string InitStatInfo {
            get {
                return ResourceManager.GetString("InitStatInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 페이지 중.
        /// </summary>
        internal static string InPage {
            get {
                return ResourceManager.GetString("InPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 자판 데이터 경로.
        /// </summary>
        internal static string KeyDataPath {
            get {
                return ResourceManager.GetString("KeyDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Training.
        /// </summary>
        internal static string KeyPrac {
            get {
                return ResourceManager.GetString("KeyPrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 자판 위의 글자들 각각의 자리를 연습합니다..
        /// </summary>
        internal static string KeyPracDesc {
            get {
                return ResourceManager.GetString("KeyPracDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연습하고 싶은 키의 위치를 클릭하여 설정/해제하세요..
        /// </summary>
        internal static string KeyPracHelp {
            get {
                return ResourceManager.GetString("KeyPracHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 한국어.
        /// </summary>
        internal static string Korean {
            get {
                return ResourceManager.GetString("Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 가장 많이 틀린 키.
        /// </summary>
        internal static string MostWrongKey {
            get {
                return ResourceManager.GetString("MostWrongKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연습한 문장 수.
        /// </summary>
        internal static string NumPracSen {
            get {
                return ResourceManager.GetString("NumPracSen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연습 데이터 경로.
        /// </summary>
        internal static string PracDataPath {
            get {
                return ResourceManager.GetString("PracDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 문장 무작위 배열.
        /// </summary>
        internal static string RanSenLoc {
            get {
                return ResourceManager.GetString("RanSenLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 문장연습.
        /// </summary>
        internal static string SenPrac {
            get {
                return ResourceManager.GetString("SenPrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 짧은 길이의 문장으로 나누어 연습합니다..
        /// </summary>
        internal static string SenPracDesc {
            get {
                return ResourceManager.GetString("SenPracDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연습하고 싶은 글을 클릭하여 선택하세요..
        /// </summary>
        internal static string SenPracHelp {
            get {
                return ResourceManager.GetString("SenPracHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연습 자판.
        /// </summary>
        internal static string SetKeyboard {
            get {
                return ResourceManager.GetString("SetKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연습 데이터.
        /// </summary>
        internal static string SetPracData {
            get {
                return ResourceManager.GetString("SetPracData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SetProgramLang {
            get {
                return ResourceManager.GetString("SetProgramLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연습 시작.
        /// </summary>
        internal static string StartPrac {
            get {
                return ResourceManager.GetString("StartPrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 음절연습.
        /// </summary>
        internal static string SylPrac {
            get {
                return ResourceManager.GetString("SylPrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  음절 단위로 입력하여 연습을 진행합니다. (한글 한정) .
        /// </summary>
        internal static string SylPracDesc {
            get {
                return ResourceManager.GetString("SylPracDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2350자는 현대 한글 음절 중 가장 사용 빈도가 높은 2350자로 연습합니다..
        /// </summary>
        internal static string SylPracHelp {
            get {
                return ResourceManager.GetString("SylPracHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O&apos;zbek.
        /// </summary>
        internal static string Uzbek {
            get {
                return ResourceManager.GetString("Uzbek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택된 자판 데이터.
        /// </summary>
        internal static string WarnMsg1 {
            get {
                return ResourceManager.GetString("WarnMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 선택된 연습 데이터.
        /// </summary>
        internal static string WarnMsg2 {
            get {
                return ResourceManager.GetString("WarnMsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 를 삭제하시겠습니까?.
        /// </summary>
        internal static string WarnMsg3 {
            get {
                return ResourceManager.GetString("WarnMsg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 의 통계 정보를 삭제하시겠습니까?.
        /// </summary>
        internal static string WarnMsg4 {
            get {
                return ResourceManager.GetString("WarnMsg4", resourceCulture);
            }
        }
    }
}
