//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenTyping.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangStr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangStr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenTyping.Resources.Lang.LangStr", typeof(LangStr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현대적인 오픈 소스 타자연습 프로그램.
        /// </summary>
        internal static string AppDesc {
            get {
                return ResourceManager.GetString("AppDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 열린타자.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 평균 정확도.
        /// </summary>
        internal static string AvgCorrect {
            get {
                return ResourceManager.GetString("AvgCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 평균 타속.
        /// </summary>
        internal static string AvgSpeed {
            get {
                return ResourceManager.GetString("AvgSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재 자판.
        /// </summary>
        internal static string CurKeyboard {
            get {
                return ResourceManager.GetString("CurKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 현재 연습 데이터.
        /// </summary>
        internal static string CurPracData {
            get {
                return ResourceManager.GetString("CurPracData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 삭제.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 윗글쇠(Shift)  연습 제외.
        /// </summary>
        internal static string ExceptShftKey {
            get {
                return ResourceManager.GetString("ExceptShftKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 홈.
        /// </summary>
        internal static string Home1 {
            get {
                return ResourceManager.GetString("Home1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 통계 정보 초기화.
        /// </summary>
        internal static string InitStatInfo {
            get {
                return ResourceManager.GetString("InitStatInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 자판 데이터 경로.
        /// </summary>
        internal static string KeyDataPath {
            get {
                return ResourceManager.GetString("KeyDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 자리연습.
        /// </summary>
        internal static string KeyPrac {
            get {
                return ResourceManager.GetString("KeyPrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 자판 위의 글자들 각각의 자리를 연습합니다..
        /// </summary>
        internal static string KeyPracDesc {
            get {
                return ResourceManager.GetString("KeyPracDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연습하고 싶은 키의 위치를 클릭하여 설정/해제하세요..
        /// </summary>
        internal static string KeyPracHelp {
            get {
                return ResourceManager.GetString("KeyPracHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 한국어.
        /// </summary>
        internal static string Korean {
            get {
                return ResourceManager.GetString("Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 긴글연습.
        /// </summary>
        internal static string LSenPrac {
            get {
                return ResourceManager.GetString("LSenPrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 하나의 장문을 대상으로 연습합니다..
        /// </summary>
        internal static string LSenPracDesc {
            get {
                return ResourceManager.GetString("LSenPracDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 가장 많이 틀린 키.
        /// </summary>
        internal static string MostWrongKey {
            get {
                return ResourceManager.GetString("MostWrongKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연습한 문장 수.
        /// </summary>
        internal static string NumPracSen {
            get {
                return ResourceManager.GetString("NumPracSen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연습 데이터 경로.
        /// </summary>
        internal static string PracDataPath {
            get {
                return ResourceManager.GetString("PracDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 문장 무작위 배열.
        /// </summary>
        internal static string RanSenLoc {
            get {
                return ResourceManager.GetString("RanSenLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 문장연습.
        /// </summary>
        internal static string SenPrac {
            get {
                return ResourceManager.GetString("SenPrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 짧은 길이의 문장으로 나누어 연습합니다..
        /// </summary>
        internal static string SenPracDesc {
            get {
                return ResourceManager.GetString("SenPracDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연습하고 싶은 글을 클릭하여 선택하세요..
        /// </summary>
        internal static string SenPracHelp {
            get {
                return ResourceManager.GetString("SenPracHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연습 자판.
        /// </summary>
        internal static string SetKeyboard {
            get {
                return ResourceManager.GetString("SetKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연습 데이터.
        /// </summary>
        internal static string SetPracData {
            get {
                return ResourceManager.GetString("SetPracData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SetProgramLang {
            get {
                return ResourceManager.GetString("SetProgramLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 연습 시작.
        /// </summary>
        internal static string StartPrac {
            get {
                return ResourceManager.GetString("StartPrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O&apos;zbek.
        /// </summary>
        internal static string Uzbek {
            get {
                return ResourceManager.GetString("Uzbek", resourceCulture);
            }
        }
    }
}
